package TunnelProjection.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Horizontal;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.openapi.editor.menus.transformation.SPropertyInfo;
import jetbrains.mps.nodeEditor.cells.EditorCell_Property;
import jetbrains.mps.nodeEditor.cells.SPropertyAccessor;
import jetbrains.mps.nodeEditor.cellMenu.SPropertySubstituteInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import java.util.Objects;
import jetbrains.mps.lang.core.behavior.PropertyAttribute__BehaviorDescriptor;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.openapi.editor.update.AttributeKind;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import de.itemis.mps.editor.diagram.runtime.jgraph.BaseDiagramECell;
import de.itemis.mps.editor.diagram.runtime.EditorUtil;
import de.itemis.mps.editor.diagram.runtime.jgraph.DiagramCreationContext;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import de.itemis.mps.editor.diagram.runtime.DiagramContext;
import de.itemis.mps.editor.diagram.runtime.ContextVariables;
import de.itemis.mps.editor.diagram.runtime.model.IDiagramAccessor;
import de.itemis.mps.editor.diagram.runtime.model.AbstractDiagramAccessor;
import java.util.List;
import de.itemis.mps.editor.diagram.runtime.model.IDiagramElementAccessor;
import de.itemis.mps.editor.diagram.runtime.model.IAccessorFactory;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import de.itemis.mps.editor.diagram.runtime.model.IConnectionType;
import java.util.Collections;
import de.itemis.mps.editor.diagram.runtime.model.GeneratedConnectionType;
import de.itemis.mps.editor.diagram.runtime.model.IConnectionEndpoint;
import de.itemis.mps.editor.diagram.runtime.model.DiagramModel;
import de.itemis.mps.editor.diagram.runtime.model.IPaletteEntryProvider;
import de.itemis.mps.editor.diagram.runtime.model.CompositePaletteEntryProvider;
import de.itemis.mps.editor.diagram.runtime.model.AbstractPaletteEntryProvider;
import de.itemis.mps.editor.diagram.runtime.model.IPaletteEntry;
import jetbrains.mps.baseLanguage.logging.runtime.model.LoggingRuntime;
import org.apache.log4j.Level;
import de.itemis.mps.editor.diagram.runtime.model.AbstractPaletteEntry;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import de.itemis.mps.editor.diagram.runtime.jgraph.SubDiagramECell;
import de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell;
import de.itemis.mps.editor.diagram.runtime.jgraph.RootDCell;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

/*package*/ class TunnelOverview_EditorBuilder_a extends AbstractEditorBuilder {
  private static final Logger LOG = LogManager.getLogger(TunnelOverview_EditorBuilder_a.class);
  @NotNull
  private SNode myNode;

  public TunnelOverview_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createCollection_0();
  }

  private EditorCell createCollection_0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_w8v2k5_a");
    editorCell.setBig(true);
    setCellContext(editorCell);
    editorCell.addEditorCell(createCollection_1());
    editorCell.addEditorCell(createConstant_1());
    editorCell.addEditorCell(createDiagram_1());
    return editorCell;
  }
  private EditorCell createCollection_1() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Horizontal());
    editorCell.setCellId("Collection_w8v2k5_a0");
    editorCell.addEditorCell(createConstant_0());
    editorCell.addEditorCell(createProperty_0());
    return editorCell;
  }
  private EditorCell createConstant_0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "Layout");
    editorCell.setCellId("Constant_w8v2k5_a0a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_0() {
    getCellFactory().pushCellContext();
    try {
      final SProperty property = PROPS.name$tAp1;
      getCellFactory().setPropertyInfo(new SPropertyInfo(myNode, property));
      EditorCell_Property editorCell = EditorCell_Property.create(getEditorContext(), new SPropertyAccessor(myNode, property, false, false), myNode);
      editorCell.setDefaultText("<no name>");
      editorCell.setCellId("property_name");
      editorCell.setSubstituteInfo(new SPropertySubstituteInfo(editorCell, property));
      setCellContext(editorCell);
      Iterable<SNode> propertyAttributes = SNodeOperations.ofConcept(AttributeOperations.getAttributeList(myNode, new IAttributeDescriptor.AllAttributes()), CONCEPTS.PropertyAttribute$jT);
      Iterable<SNode> currentPropertyAttributes = Sequence.fromIterable(propertyAttributes).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return Objects.equals(PropertyAttribute__BehaviorDescriptor.getProperty_id1avfQ4BBzOo.invoke(it), property);
        }
      });
      if (Sequence.fromIterable(currentPropertyAttributes).isNotEmpty()) {
        EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
        return manager.createNodeRoleAttributeCell(Sequence.fromIterable(currentPropertyAttributes).first(), AttributeKind.PROPERTY, editorCell);
      } else
      return editorCell;
    } finally {
      getCellFactory().popCellContext();
    }
  }
  private EditorCell createConstant_1() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "*******************************************");
    editorCell.setCellId("Constant_w8v2k5_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createDiagram_0(final EditorContext editorContext, final SNode node) {
    final Wrappers._T<BaseDiagramECell> editorCell = new Wrappers._T<BaseDiagramECell>(null);

    EditorUtil.noCaching(editorContext, new Runnable() {
      public void run() {
        DiagramCreationContext.createDiagram(new _FunctionTypes._void_P0_E0() {
          public void invoke() {
            DiagramContext.withContext(node, new _FunctionTypes._return_P0_E0<BaseDiagramECell>() {
              public BaseDiagramECell invoke() {
                return editorCell.value;
              }
            }, new Runnable() {
              public void run() {
                ContextVariables.withValue("thisNode", node, new Runnable() {
                  public void run() {
                    final ContextVariables _variablesContext = ContextVariables.getCurrent();
                    IDiagramAccessor accessor = new AbstractDiagramAccessor(node) {
                      public List<? extends IDiagramElementAccessor> getElements(IAccessorFactory accessorFactory) {
                        final List<IDiagramElementAccessor> elements = new ArrayList<IDiagramElementAccessor>();
                        for (SNode e : ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.straightRoads$Lh$z))) {
                          elements.addAll(accessorFactory.fromSNode(e));
                        }
                        for (SNode e : ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.tunnels$XEk2))) {
                          elements.addAll(accessorFactory.fromSNode(e));
                        }
                        for (SNode e : Sequence.fromIterable(new Object() {
                          public Iterable<SNode> query() {
                            return SLinkOperations.collectMany(SLinkOperations.collectMany(SLinkOperations.getChildren(node, LINKS.tunnels$XEk2), LINKS.holes$OmIQ), LINKS.leftPoints$jm9$);
                          }
                        }.query())) {
                          elements.addAll(accessorFactory.fromSNode(e, false));
                        }
                        for (SNode e : Sequence.fromIterable(new Object() {
                          public Iterable<SNode> query() {
                            return SLinkOperations.collectMany(SLinkOperations.collectMany(SLinkOperations.getChildren(node, LINKS.tunnels$XEk2), LINKS.holes$OmIQ), LINKS.rightPoints$jm8A);
                          }
                        }.query())) {
                          elements.addAll(accessorFactory.fromSNode(e, false));
                        }
                        for (SNode e : Sequence.fromIterable(new Object() {
                          public Iterable<SNode> query() {
                            // *** Left Point to Tunnel Hole Connection *** 
                            List<SNode> pointToHoleConections = new ArrayList<SNode>();
                            List<SNode> leftPoints = Sequence.fromIterable(SLinkOperations.collectMany(SLinkOperations.collectMany(SLinkOperations.getChildren(node, LINKS.tunnels$XEk2), LINKS.holes$OmIQ), LINKS.leftPoints$jm9$)).toListSequence();
                            for (SNode leftPoint : ListSequence.fromList(leftPoints)) {
                              ListSequence.fromList(pointToHoleConections).addElement(SLinkOperations.getTarget(leftPoint, LINKS.leftConnect$JRGP));
                            }
                            return pointToHoleConections;
                          }
                        }.query())) {
                          elements.addAll(accessorFactory.fromSNode(e, false));
                        }
                        for (SNode e : Sequence.fromIterable(new Object() {
                          public Iterable<SNode> query() {
                            // *** Tunnel Hole to Right Point Connection *** 
                            List<SNode> holePointConnections = new ArrayList<SNode>();

                            for (SNode hole : Sequence.fromIterable(SLinkOperations.collectMany(SLinkOperations.getChildren(node, LINKS.tunnels$XEk2), LINKS.holes$OmIQ))) {
                              ListSequence.fromList(holePointConnections).addSequence(ListSequence.fromList(SLinkOperations.getChildren(hole, LINKS.rightPointReferences$VxsM)));
                            }
                            return holePointConnections;
                          }
                        }.query())) {
                          elements.addAll(accessorFactory.fromSNode(e, false));
                        }
                        for (SNode e : Sequence.fromIterable(new Object() {
                          public Iterable<SNode> query() {
                            // *** Road to Road Connections *** 
                            List<SNode> roadConnections = new ArrayList<SNode>();

                            for (SNode road : ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.straightRoads$Lh$z))) {
                              ListSequence.fromList(roadConnections).addSequence(ListSequence.fromList(SLinkOperations.getChildren(road, LINKS.roadConnections$1_Il)));
                            }
                            return roadConnections;
                          }
                        }.query())) {
                          elements.addAll(accessorFactory.fromSNode(e, false));
                        }
                        for (SNode e : Sequence.fromIterable(new Object() {
                          public Iterable<SNode> query() {
                            // *** Road to Left Point Connection *** 
                            List<SNode> roadToLeftPointConnections = new ArrayList<SNode>();

                            for (SNode road : ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.straightRoads$Lh$z))) {
                              if ((SLinkOperations.getTarget(road, LINKS.leftPointConnection$uDEV) != null)) {
                                ListSequence.fromList(roadToLeftPointConnections).addElement(SLinkOperations.getTarget(road, LINKS.leftPointConnection$uDEV));
                              }
                            }
                            return roadToLeftPointConnections;
                          }
                        }.query())) {
                          elements.addAll(accessorFactory.fromSNode(e, false));
                        }
                        for (SNode e : Sequence.fromIterable(new Object() {
                          public Iterable<SNode> query() {
                            // *** Point to Road Connection *** 
                            List<SNode> pointToRoadConnection = new ArrayList<SNode>();

                            for (SNode rightPoint : Sequence.fromIterable(SLinkOperations.collectMany(SLinkOperations.collectMany(SLinkOperations.getChildren(node, LINKS.tunnels$XEk2), LINKS.holes$OmIQ), LINKS.rightPoints$jm8A))) {
                              if ((SLinkOperations.getTarget(rightPoint, LINKS.roadReference$Bbhk) != null)) {
                                ListSequence.fromList(pointToRoadConnection).addElement(SLinkOperations.getTarget(rightPoint, LINKS.roadReference$Bbhk));
                              }
                            }
                            return pointToRoadConnection;
                          }
                        }.query())) {
                          elements.addAll(accessorFactory.fromSNode(e, false));
                        }
                        return elements;
                      }
                      @Override
                      public List<IConnectionType> getConnectionTypes() {
                        List<IConnectionType> connectionTypes = new ArrayList<IConnectionType>();
                        connectionTypes.addAll(Collections.singletonList(new GeneratedConnectionType() {
                          public String getName() {
                            return "Point to Hole Connection";
                          }
                          @Override
                          public void create(final IConnectionEndpoint from, final IConnectionEndpoint to) {
                            final SNode fromNode = SNodeOperations.cast(from.getSNode(), CONCEPTS.LeftTunnelPoint$5I);
                            final SNode toNode = SNodeOperations.cast(to.getSNode(), CONCEPTS.TunnelHole$g8);
                            final String fromPort = from.getPortName();
                            final String toPort = to.getPortName();

                            {
                              SNode pointToHoleConnection = SLinkOperations.setNewChild(fromNode, LINKS.leftConnect$JRGP, CONCEPTS.TunnelHoleReference$m9);
                              SLinkOperations.setTarget(pointToHoleConnection, LINKS.leftConnect$ZaFw, toNode);
                            }
                          }
                          @Override
                          public boolean isValidStart(IConnectionEndpoint from) {
                            final SNode fromNode = SNodeOperations.as(from.getSNode(), CONCEPTS.LeftTunnelPoint$5I);
                            if (fromNode == null) {
                              return false;
                            }
                            final String fromPort = from.getPortName();
                            return true;
                          }
                          @Override
                          public boolean isValidEnd(IConnectionEndpoint to) {
                            final SNode toNode = SNodeOperations.as(to.getSNode(), CONCEPTS.TunnelHole$g8);
                            if (toNode == null) {
                              return false;
                            }
                            final String toPort = to.getPortName();
                            return true;
                          }
                        }));
                        connectionTypes.addAll(Collections.singletonList(new GeneratedConnectionType() {
                          public String getName() {
                            return "Hole to Point Connection";
                          }
                          @Override
                          public void create(final IConnectionEndpoint from, final IConnectionEndpoint to) {
                            final SNode fromNode = SNodeOperations.cast(from.getSNode(), CONCEPTS.TunnelHole$g8);
                            final SNode toNode = SNodeOperations.cast(to.getSNode(), CONCEPTS.RightTunnelPoint$$f);
                            final String fromPort = from.getPortName();
                            final String toPort = to.getPortName();

                            {
                              SNode holeToPointConnection = SLinkOperations.addNewChild(fromNode, LINKS.rightPointReferences$VxsM, CONCEPTS.RightPointReference$56);
                              SLinkOperations.setTarget(holeToPointConnection, LINKS.rightPointConnection$IrX0, toNode);
                            }
                          }
                          @Override
                          public boolean isValidStart(IConnectionEndpoint from) {
                            final SNode fromNode = SNodeOperations.as(from.getSNode(), CONCEPTS.TunnelHole$g8);
                            if (fromNode == null) {
                              return false;
                            }
                            final String fromPort = from.getPortName();
                            return true;
                          }
                          @Override
                          public boolean isValidEnd(IConnectionEndpoint to) {
                            final SNode toNode = SNodeOperations.as(to.getSNode(), CONCEPTS.RightTunnelPoint$$f);
                            if (toNode == null) {
                              return false;
                            }
                            final String toPort = to.getPortName();
                            return true;
                          }
                        }));
                        connectionTypes.addAll(Collections.singletonList(new GeneratedConnectionType() {
                          public String getName() {
                            return "Road to Road Connection";
                          }
                          @Override
                          public void create(final IConnectionEndpoint from, final IConnectionEndpoint to) {
                            final SNode fromNode = SNodeOperations.cast(from.getSNode(), CONCEPTS.StraightRoad$CO);
                            final SNode toNode = SNodeOperations.cast(to.getSNode(), CONCEPTS.StraightRoad$CO);
                            final String fromPort = from.getPortName();
                            final String toPort = to.getPortName();

                            {
                              SNode roadToRoadConnection = SLinkOperations.addNewChild(fromNode, LINKS.roadConnections$1_Il, CONCEPTS.StraightRoadRef$mj);
                              SLinkOperations.setTarget(roadToRoadConnection, LINKS.roadConnection$FS6w, toNode);
                            }
                          }
                          @Override
                          public boolean isValidStart(IConnectionEndpoint from) {
                            final SNode fromNode = SNodeOperations.as(from.getSNode(), CONCEPTS.StraightRoad$CO);
                            if (fromNode == null) {
                              return false;
                            }
                            final String fromPort = from.getPortName();
                            return true;
                          }
                          @Override
                          public boolean isValidEnd(IConnectionEndpoint to) {
                            final SNode toNode = SNodeOperations.as(to.getSNode(), CONCEPTS.StraightRoad$CO);
                            if (toNode == null) {
                              return false;
                            }
                            final String toPort = to.getPortName();
                            return true;
                          }
                        }));
                        connectionTypes.addAll(Collections.singletonList(new GeneratedConnectionType() {
                          public String getName() {
                            return "Road to Point Connection";
                          }
                          @Override
                          public void create(final IConnectionEndpoint from, final IConnectionEndpoint to) {
                            final SNode fromNode = SNodeOperations.cast(from.getSNode(), CONCEPTS.StraightRoad$CO);
                            final SNode toNode = SNodeOperations.cast(to.getSNode(), CONCEPTS.LeftTunnelPoint$5I);
                            final String fromPort = from.getPortName();
                            final String toPort = to.getPortName();

                            {
                              SNode roadToPointConnection = SLinkOperations.setNewChild(fromNode, LINKS.leftPointConnection$uDEV, CONCEPTS.LeftPointReference$GL);
                              SLinkOperations.setTarget(roadToPointConnection, LINKS.leftPointConnect$Vlnw, toNode);
                            }
                          }
                          @Override
                          public boolean isValidStart(IConnectionEndpoint from) {
                            final SNode fromNode = SNodeOperations.as(from.getSNode(), CONCEPTS.StraightRoad$CO);
                            if (fromNode == null) {
                              return false;
                            }
                            final String fromPort = from.getPortName();
                            return true;
                          }
                          @Override
                          public boolean isValidEnd(IConnectionEndpoint to) {
                            final SNode toNode = SNodeOperations.as(to.getSNode(), CONCEPTS.LeftTunnelPoint$5I);
                            if (toNode == null) {
                              return false;
                            }
                            final String toPort = to.getPortName();
                            return true;
                          }
                        }));
                        connectionTypes.addAll(Collections.singletonList(new GeneratedConnectionType() {
                          public String getName() {
                            return "Point to Road Connection";
                          }
                          @Override
                          public void create(final IConnectionEndpoint from, final IConnectionEndpoint to) {
                            final SNode fromNode = SNodeOperations.cast(from.getSNode(), CONCEPTS.RightTunnelPoint$$f);
                            final SNode toNode = SNodeOperations.cast(to.getSNode(), CONCEPTS.StraightRoad$CO);
                            final String fromPort = from.getPortName();
                            final String toPort = to.getPortName();

                            {
                              SNode pointToRoadConnection = SLinkOperations.setNewChild(fromNode, LINKS.roadReference$Bbhk, CONCEPTS.StraightRoadRef$mj);
                              SLinkOperations.setTarget(pointToRoadConnection, LINKS.roadConnection$FS6w, toNode);
                            }
                          }
                          @Override
                          public boolean isValidStart(IConnectionEndpoint from) {
                            final SNode fromNode = SNodeOperations.as(from.getSNode(), CONCEPTS.RightTunnelPoint$$f);
                            if (fromNode == null) {
                              return false;
                            }
                            final String fromPort = from.getPortName();
                            return true;
                          }
                          @Override
                          public boolean isValidEnd(IConnectionEndpoint to) {
                            final SNode toNode = SNodeOperations.as(to.getSNode(), CONCEPTS.StraightRoad$CO);
                            if (toNode == null) {
                              return false;
                            }
                            final String toPort = to.getPortName();
                            return true;
                          }
                        }));
                        return connectionTypes;
                      }
                    };

                    DiagramModel model = DiagramModel.getModel(editorContext, node, "5159374792462217178", accessor);

                    IPaletteEntryProvider paletteEntryProvider = new CompositePaletteEntryProvider(new AbstractPaletteEntryProvider() {
                      @Override
                      public Iterable<IPaletteEntry> getEntries() {
                        List<IPaletteEntry> entries = ListSequence.fromList(new ArrayList<IPaletteEntry>());
                        LoggingRuntime.logMsgView(Level.INFO, "REEEEERA", TunnelOverview_EditorBuilder_a.class, null, null);
                        ListSequence.fromList(entries).addElement(new AbstractPaletteEntry() {
                          @NotNull
                          @Override
                          public String getText() {
                            return CONCEPTS.Tunnel$ji.getName();
                          }
                          @Nullable
                          @Override
                          public SNode execute() {
                            SNode newTunnel = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb761L, "TunnelProjection.structure.Tunnel"));
                            return SModelOperations.addRootNode(SNodeOperations.getModel(node), newTunnel);
                          }
                        });
                        return entries;
                      }
                    });
                    model.setPaletteEntryProvider(paletteEntryProvider);

                    if (DiagramCreationContext.isSubdiagram()) {
                      editorCell.value = new SubDiagramECell(editorContext, node, model);
                    } else {
                      editorCell.value = new RootDiagramECell(editorContext, node, model);
                    }
                    editorCell.value.setCellId("Diagram_w8v2k5_c0");
                    if (editorCell.value.getContextGraph() != null) {
                      Object defaultParent = editorCell.value.getContextGraph().getDefaultParent();
                      if (defaultParent instanceof RootDCell) {
                        ((RootDCell) defaultParent).resetButtonConfig();
                      }
                    }
                  }
                });
              }
            });
          }
        });
      }
    });

    return editorCell.value;
  }
  private EditorCell createDiagram_1() {
    return createDiagram_0(getEditorContext(), myNode);
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$tAp1 = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PropertyAttribute$jT = MetaAdapterFactory.getConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da56L, "jetbrains.mps.lang.core.structure.PropertyAttribute");
    /*package*/ static final SConcept LeftTunnelPoint$5I = MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb75aL, "TunnelProjection.structure.LeftTunnelPoint");
    /*package*/ static final SConcept TunnelHole$g8 = MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c14804L, "TunnelProjection.structure.TunnelHole");
    /*package*/ static final SConcept TunnelHoleReference$m9 = MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804cd85a3L, "TunnelProjection.structure.TunnelHoleReference");
    /*package*/ static final SConcept RightTunnelPoint$$f = MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb76fL, "TunnelProjection.structure.RightTunnelPoint");
    /*package*/ static final SConcept RightPointReference$56 = MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1e674eba2c398dc1L, "TunnelProjection.structure.RightPointReference");
    /*package*/ static final SConcept StraightRoad$CO = MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804955038L, "TunnelProjection.structure.StraightRoad");
    /*package*/ static final SConcept StraightRoadRef$mj = MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c1fb06L, "TunnelProjection.structure.StraightRoadRef");
    /*package*/ static final SConcept LeftPointReference$GL = MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x13e8a493a7663348L, "TunnelProjection.structure.LeftPointReference");
    /*package*/ static final SConcept Tunnel$ji = MetaAdapterFactory.getConcept(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb761L, "TunnelProjection.structure.Tunnel");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink straightRoads$Lh$z = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x4799c809c7d0add2L, 0x1269a4680495503bL, "straightRoads");
    /*package*/ static final SContainmentLink tunnels$XEk2 = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x4799c809c7d0add2L, 0x1269a46804c41f1aL, "tunnels");
    /*package*/ static final SContainmentLink holes$OmIQ = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb761L, 0x1e674eba2c62fc07L, "holes");
    /*package*/ static final SContainmentLink leftPoints$jm9$ = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c14804L, 0x1269a46804c1480cL, "leftPoints");
    /*package*/ static final SContainmentLink rightPoints$jm8A = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c14804L, 0x1269a46804c1480aL, "rightPoints");
    /*package*/ static final SContainmentLink leftConnect$JRGP = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb75aL, 0x1269a46804cd859fL, "leftConnect");
    /*package*/ static final SContainmentLink rightPointReferences$VxsM = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c14804L, 0x1e674eba2c63b2a8L, "rightPointReferences");
    /*package*/ static final SContainmentLink roadConnections$1_Il = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804955038L, 0x1e674eba2c5843a7L, "roadConnections");
    /*package*/ static final SContainmentLink leftPointConnection$uDEV = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804955038L, 0x13e8a493a766334bL, "leftPointConnection");
    /*package*/ static final SContainmentLink roadReference$Bbhk = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb76fL, 0x13e8a493a771deebL, "roadReference");
    /*package*/ static final SReferenceLink leftConnect$ZaFw = MetaAdapterFactory.getReferenceLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804cd85a3L, 0x1269a46804cd85a4L, "leftConnect");
    /*package*/ static final SReferenceLink rightPointConnection$IrX0 = MetaAdapterFactory.getReferenceLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1e674eba2c398dc1L, 0x1e674eba2c398dc2L, "rightPointConnection");
    /*package*/ static final SReferenceLink roadConnection$FS6w = MetaAdapterFactory.getReferenceLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c1fb06L, 0x1269a46804c1fb07L, "roadConnection");
    /*package*/ static final SReferenceLink leftPointConnect$Vlnw = MetaAdapterFactory.getReferenceLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x13e8a493a7663348L, 0x13e8a493a7663349L, "leftPointConnect");
  }
}
