package TunnelProjection.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public final class OpenOrCloseBeamForRoad_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public OpenOrCloseBeamForRoad_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:2b869ca2-ccf5-4cfa-ac42-87fb5d120400(TunnelProjection.intentions)", "3321041496540146514"));
  }
  @Override
  public String getPresentation() {
    return "OpenOrCloseBeamForRoad";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }
  private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return (SLinkOperations.getTarget(node, LINKS.hasBeam$DTdB) != null);
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      if (SPropertyOperations.getBoolean(SLinkOperations.getTarget(node, LINKS.hasBeam$DTdB), PROPS.isClosed$oMz0)) {
        return "Open Beam";
      } else {
        return "Close Beam";
      }
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      if (SPropertyOperations.getBoolean(SLinkOperations.getTarget(node, LINKS.hasBeam$DTdB), PROPS.isClosed$oMz0)) {
        SPropertyOperations.set(SLinkOperations.getTarget(node, LINKS.hasBeam$DTdB), PROPS.isClosed$oMz0, false);
      } else {
        SPropertyOperations.set(SLinkOperations.getTarget(node, LINKS.hasBeam$DTdB), PROPS.isClosed$oMz0, true);
      }
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return OpenOrCloseBeamForRoad_Intention.this;
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink hasBeam$DTdB = MetaAdapterFactory.getContainmentLink(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804955038L, 0x261858895fee0ab1L, "hasBeam");
  }

  private static final class PROPS {
    /*package*/ static final SProperty isClosed$oMz0 = MetaAdapterFactory.getProperty(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x261858895fee0a81L, 0x261858895ff95709L, "isClosed");
  }
}
