package TunnelProjection.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SemaphoreLights extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SemaphoreLights() {
    super(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x261858895ffc2fe6L, "SemaphoreLights", "r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/2745041319926444006");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Green_0 = new EnumerationDescriptor.MemberDescriptor("Green", "Green", 0x261858895ffc2fe7L, "r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/2745041319926444007");
  private final EnumerationDescriptor.MemberDescriptor myMember_Orange_0 = new EnumerationDescriptor.MemberDescriptor("Orange", "Orange", 0x261858895ffc2fe8L, "r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/2745041319926444008");
  private final EnumerationDescriptor.MemberDescriptor myMember_Red_0 = new EnumerationDescriptor.MemberDescriptor("Red", "Red", 0x261858895ffc2febL, "r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/2745041319926444011");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x261858895ffc2fe6L, 0x261858895ffc2fe7L, 0x261858895ffc2fe8L, 0x261858895ffc2febL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Green_0, myMember_Orange_0, myMember_Red_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Green_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Green":
        return myMember_Green_0;
      case "Orange":
        return myMember_Orange_0;
      case "Red":
        return myMember_Red_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
