package TunnelProjection.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RoadType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RoadType() {
    super(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a468049550c0L, "RoadType", "r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331897770176");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Bicycle_0 = new EnumerationDescriptor.MemberDescriptor("Bicycle", "Bicycle", 0x1269a468049550c1L, "r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331897770177");
  private final EnumerationDescriptor.MemberDescriptor myMember_Emergency_0 = new EnumerationDescriptor.MemberDescriptor("Emergency", "Emergency", 0x1269a468049550c2L, "r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331897770178");
  private final EnumerationDescriptor.MemberDescriptor myMember_Car_0 = new EnumerationDescriptor.MemberDescriptor("Car", "Car", 0x1269a468049550c5L, "r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331897770181");
  private final EnumerationDescriptor.MemberDescriptor myMember_Highway_0 = new EnumerationDescriptor.MemberDescriptor("Highway", "Highway", 0x1269a468049550c9L, "r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331897770185");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a468049550c0L, 0x1269a468049550c1L, 0x1269a468049550c2L, 0x1269a468049550c5L, 0x1269a468049550c9L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Bicycle_0, myMember_Emergency_0, myMember_Car_0, myMember_Highway_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Bicycle":
        return myMember_Bicycle_0;
      case "Emergency":
        return myMember_Emergency_0;
      case "Car":
        return myMember_Car_0;
      case "Highway":
        return myMember_Highway_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
