package TunnelProjection.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCurvyRoad = createDescriptorForCurvyRoad();
  /*package*/ final ConceptDescriptor myConceptLeftPointReference = createDescriptorForLeftPointReference();
  /*package*/ final ConceptDescriptor myConceptLeftTunnelPoint = createDescriptorForLeftTunnelPoint();
  /*package*/ final ConceptDescriptor myConceptRightPointReference = createDescriptorForRightPointReference();
  /*package*/ final ConceptDescriptor myConceptRightTunnelPoint = createDescriptorForRightTunnelPoint();
  /*package*/ final ConceptDescriptor myConceptStraightRoad = createDescriptorForStraightRoad();
  /*package*/ final ConceptDescriptor myConceptStraightRoadRef = createDescriptorForStraightRoadRef();
  /*package*/ final ConceptDescriptor myConceptTunnel = createDescriptorForTunnel();
  /*package*/ final ConceptDescriptor myConceptTunnelHole = createDescriptorForTunnelHole();
  /*package*/ final ConceptDescriptor myConceptTunnelHoleReference = createDescriptorForTunnelHoleReference();
  /*package*/ final ConceptDescriptor myConceptTunnelOverview = createDescriptorForTunnelOverview();
  /*package*/ final EnumerationDescriptor myEnumerationConnectionType = new EnumerationDescriptor_ConnectionType();
  /*package*/ final EnumerationDescriptor myEnumerationRoadType = new EnumerationDescriptor_RoadType();
  /*package*/ final EnumerationDescriptor myEnumerationTunnelPointType = new EnumerationDescriptor_TunnelPointType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCurvyRoad, myConceptLeftPointReference, myConceptLeftTunnelPoint, myConceptRightPointReference, myConceptRightTunnelPoint, myConceptStraightRoad, myConceptStraightRoadRef, myConceptTunnel, myConceptTunnelHole, myConceptTunnelHoleReference, myConceptTunnelOverview);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CurvyRoad:
        return myConceptCurvyRoad;
      case LanguageConceptSwitch.LeftPointReference:
        return myConceptLeftPointReference;
      case LanguageConceptSwitch.LeftTunnelPoint:
        return myConceptLeftTunnelPoint;
      case LanguageConceptSwitch.RightPointReference:
        return myConceptRightPointReference;
      case LanguageConceptSwitch.RightTunnelPoint:
        return myConceptRightTunnelPoint;
      case LanguageConceptSwitch.StraightRoad:
        return myConceptStraightRoad;
      case LanguageConceptSwitch.StraightRoadRef:
        return myConceptStraightRoadRef;
      case LanguageConceptSwitch.Tunnel:
        return myConceptTunnel;
      case LanguageConceptSwitch.TunnelHole:
        return myConceptTunnelHole;
      case LanguageConceptSwitch.TunnelHoleReference:
        return myConceptTunnelHoleReference;
      case LanguageConceptSwitch.TunnelOverview:
        return myConceptTunnelOverview;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationConnectionType, myEnumerationRoadType, myEnumerationTunnelPointType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCurvyRoad() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "CurvyRoad", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a468049550ceL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331897770190");
    b.version(2);
    b.property("type", 0x1269a468049550d1L).type(MetaIdFactory.dataTypeId(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a468049550c0L)).origin("1326772331897770193").done();
    b.property("angle", 0x1269a468049550d7L).type(PrimitiveTypeId.INTEGER).origin("1326772331897770199").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLeftPointReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "LeftPointReference", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x13e8a493a7663348L);
    b.class_(false, false, false);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1434577435393143624");
    b.version(2);
    b.associate("leftPointConnect", 0x13e8a493a7663349L).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb75aL).optional(false).origin("1434577435393143625").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLeftTunnelPoint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "LeftTunnelPoint", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb75aL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331900548954");
    b.version(2);
    b.property("x", 0x1269a46804bfb766L).type(PrimitiveTypeId.INTEGER).origin("1326772331900548966").done();
    b.property("y", 0x1269a46804bfb76cL).type(PrimitiveTypeId.INTEGER).origin("1326772331900548972").done();
    b.property("entryPoint", 0x1269a46804bfb92eL).type(PrimitiveTypeId.BOOLEAN).origin("1326772331900549422").done();
    b.property("leftToRightDirection", 0x3a88284cfa7f3ad3L).type(PrimitiveTypeId.BOOLEAN).origin("4217665362117737171").done();
    b.aggregate("roadConnection", 0x1269a46804bfb777L).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c1fb06L).optional(false).ordered(true).multiple(false).origin("1326772331900548983").done();
    b.aggregate("leftConnect", 0x1269a46804cd859fL).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804cd85a3L).optional(false).ordered(true).multiple(false).origin("1326772331901453727").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRightPointReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "RightPointReference", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1e674eba2c398dc1L);
    b.class_(false, false, false);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/2190806305251888577");
    b.version(2);
    b.associate("rightPointConnection", 0x1e674eba2c398dc2L).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb76fL).optional(false).origin("2190806305251888578").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRightTunnelPoint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "RightTunnelPoint", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb76fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331900548975");
    b.version(2);
    b.property("x", 0x1269a46804bfb920L).type(PrimitiveTypeId.INTEGER).origin("1326772331900549408").done();
    b.property("y", 0x1269a46804bfb922L).type(PrimitiveTypeId.INTEGER).origin("1326772331900549410").done();
    b.property("isLeftPoint", 0x1269a46804bfb925L).type(PrimitiveTypeId.BOOLEAN).origin("1326772331900549413").done();
    b.property("leftToRightDirection", 0x3a88284cfa80944dL).type(PrimitiveTypeId.BOOLEAN).origin("4217665362117825613").done();
    b.associate("hole", 0x1e674eba2c6d6877L).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c14804L).optional(false).origin("2190806305255286903").done();
    b.aggregate("roadReference", 0x13e8a493a771deebL).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c1fb06L).optional(true).ordered(true).multiple(false).origin("1434577435393908459").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStraightRoad() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "StraightRoad", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804955038L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331897770040");
    b.version(2);
    b.property("type", 0x1269a468049550bdL).type(MetaIdFactory.dataTypeId(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a468049550c0L)).origin("1326772331897770173").done();
    b.property("length", 0x1269a46804959a80L).type(PrimitiveTypeId.INTEGER).origin("1326772331897789056").done();
    b.property("startX", 0x1269a46804bfb9e6L).type(PrimitiveTypeId.INTEGER).origin("1326772331900549606").done();
    b.property("startY", 0x1269a46804bfba07L).type(PrimitiveTypeId.INTEGER).origin("1326772331900549639").done();
    b.property("endX", 0x1269a46804bfba0cL).type(PrimitiveTypeId.INTEGER).origin("1326772331900549644").done();
    b.property("endY", 0x1269a46804bfba12L).type(PrimitiveTypeId.INTEGER).origin("1326772331900549650").done();
    b.property("lanes", 0x1e674eba2c584393L).type(PrimitiveTypeId.INTEGER).origin("2190806305253901203").done();
    b.property("insideTunnel", 0x1e674eba2c58439bL).type(PrimitiveTypeId.BOOLEAN).origin("2190806305253901211").done();
    b.aggregate("roadConnections", 0x1e674eba2c5843a7L).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c1fb06L).optional(true).ordered(true).multiple(true).origin("2190806305253901223").done();
    b.aggregate("leftPointConnection", 0x13e8a493a766334bL).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x13e8a493a7663348L).optional(true).ordered(true).multiple(false).origin("1434577435393143627").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStraightRoadRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "StraightRoadRef", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c1fb06L);
    b.class_(false, false, false);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331900697350");
    b.version(2);
    b.associate("roadConnection", 0x1269a46804c1fb07L).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804955038L).optional(false).origin("1326772331900697351").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTunnel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "Tunnel", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb761L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331900548961");
    b.version(2);
    b.aggregate("holes", 0x1e674eba2c62fc07L).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c14804L).optional(false).ordered(true).multiple(true).origin("2190806305254603783").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTunnelHole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "TunnelHole", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c14804L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331900651524");
    b.version(2);
    b.aggregate("leftPoints", 0x1269a46804c1480cL).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb75aL).optional(false).ordered(true).multiple(true).origin("1326772331900651532").done();
    b.aggregate("rightPoints", 0x1269a46804c1480aL).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb76fL).optional(false).ordered(true).multiple(true).origin("1326772331900651530").done();
    b.aggregate("tunnelHoleRoads", 0x1e674eba2c637e5dL).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804955038L).optional(false).ordered(true).multiple(true).origin("2190806305254637149").done();
    b.aggregate("rightPointReferences", 0x1e674eba2c63b2a8L).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1e674eba2c398dc1L).optional(false).ordered(true).multiple(true).origin("2190806305254650536").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTunnelHoleReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "TunnelHoleReference", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804cd85a3L);
    b.class_(false, false, false);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/1326772331901453731");
    b.version(2);
    b.associate("leftConnect", 0x1269a46804cd85a4L).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804c14804L).optional(false).origin("1326772331901453732").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTunnelOverview() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TunnelProjection", "TunnelOverview", 0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x4799c809c7d0add2L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6e36a64b-b1ea-431d-940e-d48e4716b989(TunnelProjection.structure)/5159374792462216658");
    b.version(2);
    b.aggregate("tunnels", 0x1269a46804c41f1aL).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804bfb761L).optional(true).ordered(true).multiple(true).origin("1326772331900837658").done();
    b.aggregate("straightRoads", 0x1269a4680495503bL).target(0x72c81d76425049a4L, 0x8dfa274e9e7a2b19L, 0x1269a46804955038L).optional(true).ordered(true).multiple(true).origin("1326772331897770043").done();
    return b.create();
  }
}
