package TunnelSketch.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TunnelDefinition_Constraints extends BaseConstraintsDescriptor {
  public TunnelDefinition_Constraints() {
    super(CONCEPTS.TunnelDefinition$Ej);
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept TunnelDefinition$Ej = MetaAdapterFactory.getConcept(0xa181095ee04c42f1L, 0x9ea7b771b750f4d2L, 0x69804428d86cddb5L, "TunnelSketch.structure.TunnelDefinition");
  }
}
